// Dev-only generator for ../netOcc.blob.ts (not imported by the scene): which vein segments of each leaf lie under a
// younger leaf's blade (pre-twist ground space). Regenerate whenever netData.blob.ts or the leaf outlines change:
//   node_modules/.bin/esbuild src/scenes/S06_Sunlight/dev/gen-occ-data.ts --bundle --platform=node \
//     --outfile=/tmp/genocc.cjs && node /tmp/genocc.cjs > src/scenes/S06_Sunlight/netOcc.blob.ts
import { occlusionMasks } from '../veins';

const masks = occlusionMasks().map((m) => {
  const bytes = new Uint8Array(Math.ceil(m.length / 8));
  m.forEach((v, i) => {
    if (v) bytes[i >> 3] |= 1 << (i & 7);
  });
  return Buffer.from(bytes).toString('base64');
});
console.log('// AUTO-GENERATED by dev/gen-occ-data.ts — per leaf, 1 bit per vein node: covered by a younger leaf (LSB first).');
console.log(`export const OCC_B64: string[] = ${JSON.stringify(masks)};`);
