// Dev-only generator for ../netData.ts (not imported by the scene). Runs the space-colonization growth once and
// packs the trees as base64 Int16 (x·10, y·10, parent, step per node). Regenerate after changing the growth:
//   node_modules/.bin/esbuild src/scenes/S06_Sunlight/dev/gen-net-data.ts --bundle --platform=node \
//     --outfile=/tmp/gen.cjs && node /tmp/gen.cjs > src/scenes/S06_Sunlight/netData.blob.ts
import { buildLeaves, buildRiver } from '../network';
import type { GrowthNode } from '../../../lib/growth';

const pack = (nodes: GrowthNode[]) => {
  const a = new Int16Array(nodes.length * 4);
  nodes.forEach((n, i) => {
    a[i * 4] = Math.round(n.x * 10);
    a[i * 4 + 1] = Math.round(n.y * 10);
    a[i * 4 + 2] = n.parent;
    a[i * 4 + 3] = n.step;
  });
  return Buffer.from(a.buffer).toString('base64');
};
const leaves = buildLeaves(true).map((l) => pack(l.nodes));
const river = pack(buildRiver(true).nodes);
console.log('// AUTO-GENERATED by dev/gen-net-data.ts — pre-grown vein / river trees (base64 Int16: x·10, y·10, parent, step).');
console.log(`export const LEAF_B64: string[] = ${JSON.stringify(leaves)};`);
console.log(`export const RIVER_B64 = ${JSON.stringify(river)};`);
