// Decoder for the pre-grown trees in netData.blob.ts (generated by dev/gen-net-data.ts from lib/growth.ts with the
// exact same attractors/seeds as network.ts). Depth, Murray radius and leaf load are recomputed here (O(n)).
import type { GrowthNode } from '../../lib/growth';
import { memo } from '../../lib/math';
import { LEAF_B64, RIVER_B64 } from './netData.blob';

function decode(b64: string): GrowthNode[] {
  const bin = atob(b64);
  const n = bin.length / 8;
  const dv = new DataView(new ArrayBuffer(bin.length));
  for (let i = 0; i < bin.length; i++) dv.setUint8(i, bin.charCodeAt(i));
  const nodes: GrowthNode[] = [];
  for (let i = 0; i < n; i++) {
    const x = dv.getInt16(i * 8, true) / 10;
    const y = dv.getInt16(i * 8 + 2, true) / 10;
    const parent = dv.getInt16(i * 8 + 4, true);
    const step = dv.getInt16(i * 8 + 6, true);
    const p = parent >= 0 ? nodes[parent] : null;
    nodes.push({ x, y, parent, step, depth: p ? p.depth + 1 : 0, radius: 1, load: 1, root: p ? p.root : 0 });
  }
  // Murray's law radii & leaf loads (children are always after parents) — as in lib/growth.ts
  const childR3 = new Float64Array(n);
  const loads = new Float64Array(n);
  const hasChild = new Uint8Array(n);
  for (let i = n - 1; i >= 0; i--) {
    const nd = nodes[i];
    if (hasChild[i]) {
      nd.radius = Math.cbrt(childR3[i]);
      nd.load = loads[i];
    }
    if (nd.parent >= 0) {
      hasChild[nd.parent] = 1;
      childR3[nd.parent] += nd.radius ** 3;
      loads[nd.parent] += nd.load;
    }
  }
  return nodes;
}

export const netNodes = (kind: 'leaf' | 'river', k: number): GrowthNode[] =>
  memo(`s06:netNodes:${kind}:${k}`, () => decode(kind === 'leaf' ? LEAF_B64[k] : RIVER_B64));
