// S02 sound cues (scene-local frames) for scripts/audio/score.py. `kind` keywords follow score.py's cue_sound():
// tick/collision/click/type -> tick, crackle/swarm -> crackle, impact/stamp -> impact, whoosh/sweep -> whoosh,
// glitch/rewind -> glitch, flash/spark/shimmer -> high bell, reveal/chime/pop -> bell. Collision frames are exact
// (taken from the recorded hard-disc simulations in sims.ts).
export interface Cue {
  frame: number;
  kind: string;
  description: string;
  intensity: number;
  pan?: number;
}

export const CUES: Cue[] = [
  { frame: 0, kind: 'silence', description: 'IN: room tone only, the lone dot of S01', intensity: 0 },
  { frame: 6, kind: 'reveal ping', description: 'the dot pings; a sonar-like wavefront reveals the blueprint grid', intensity: 0.55 },
  { frame: 14, kind: 'sweep', description: 'panel frames draw on (A then B)', intensity: 0.25 },
  { frame: 18, kind: 'pop', description: 'cell division 1 -> 2 (pinch flash)', intensity: 0.5 },
  { frame: 19, kind: 'whoosh', description: 'daughters fly up into A and down into B', intensity: 0.3 },
  { frame: 30, kind: 'pop', description: 'second division in both panels (2 -> 4 balls)', intensity: 0.4 },
  { frame: 34, kind: 'type', description: 'FIG.02 TIME-REVERSAL BLIND TEST types on; both panel clocks read ??.?? s', intensity: 0.2 },
  { frame: 50, kind: 'glitch', description: 'the word 倒放 glitches in short bursts while card 1 is up (f24-114, light)', intensity: 0.25 },
  { frame: 72, kind: 'tick', description: 'countdown 3', intensity: 0.6 },
  { frame: 82, kind: 'collision', description: '2-ball elastic collision — A and B touch on the same frame', intensity: 0.8 },
  { frame: 93, kind: 'tick', description: 'countdown 2', intensity: 0.6 },
  { frame: 114, kind: 'tick', description: 'countdown 1 (card 1 has just left)', intensity: 0.6 },
  { frame: 134, kind: 'stamp', description: '"?" stamps hit both panels (+ gutter ?); camera nudge; 分不出来。 condenses', intensity: 0.6 },
  { frame: 144, kind: 'whoosh', description: 'the "?" stamps retreat into small corner badges, clearing the panel centres', intensity: 0.2 },
  { frame: 150, kind: 'type', description: 'the law m d²x/dt² = F(x) writes on in both panels (f150-166) while 分不出来。 is still up', intensity: 0.35 },
  { frame: 160, kind: 'type', description: 'gutter: "t → −t" types on (f160-170)', intensity: 0.25 },
  { frame: 166, kind: 'type', description: 'B: t -> (−t) substitution (red brackets + minus drop in)', intensity: 0.4 },
  { frame: 174, kind: 'pop', description: 'B: the square gives birth to a twin minus sign', intensity: 0.4 },
  { frame: 176, kind: 'whoosh', description: 'card 4 「运动定律，不分正放倒放。」 condenses as card 3 diffuses (soft)', intensity: 0.15 },
  { frame: 188, kind: 'flash', description: 'B: the two minus signs ANNIHILATE (white flash + sparks), camera nudge', intensity: 0.9 },
  { frame: 190, kind: 'whoosh', description: '正放 | 倒放 unfold out of a dashed mirror axis (f190-210), 倒放 flipping from its mirror image', intensity: 0.2 },
  { frame: 192, kind: 'click', description: "B: the red brackets collapse — B's law is A's law again", intensity: 0.3 },
  { frame: 204, kind: 'chime', description: 't → −t ：不变 ✓ completes (f204-212) with a glint sweeping both equations in sync; held fully opaque to f252', intensity: 0.6 },
  { frame: 260, kind: 'sweep', description: 'plotter scan-wipe to N = 10 (counter rolls 2 -> 10)', intensity: 0.45 },
  { frame: 274, kind: 'pop', description: 'verdict "?" appears (能分辨吗？)', intensity: 0.35 },
  { frame: 278, kind: 'impact', description: 'A: cue ball breaks the 9-ball diamond (12 simultaneous contacts)', intensity: 0.7, pan: 0 },
  { frame: 279, kind: 'collision', description: 'B ball contact', intensity: 0.3 },
  { frame: 281, kind: 'collision', description: 'B ball contact', intensity: 0.3 },
  { frame: 285, kind: 'collision', description: 'B ball contact', intensity: 0.3 },
  { frame: 289, kind: 'collision', description: 'B ball contact', intensity: 0.3 },
  { frame: 291, kind: 'collision', description: 'B ball contact', intensity: 0.3 },
  { frame: 292, kind: 'collision', description: 'A ball contact', intensity: 0.3 },
  { frame: 294, kind: 'collision', description: 'A ball contact', intensity: 0.3 },
  { frame: 298, kind: 'collision', description: 'A ball contact', intensity: 0.3 },
  { frame: 302, kind: 'collision', description: 'A ball contact', intensity: 0.3 },
  { frame: 304, kind: 'collision', description: 'A ball contact', intensity: 0.3 },
  { frame: 305, kind: 'impact', description: 'B: the balls re-rack themselves into the perfect diamond and eject the cue (reverse break)', intensity: 0.6 },
  { frame: 306, kind: 'pop', description: 'verdict "!"', intensity: 0.6 },
  { frame: 314, kind: 'sweep', description: 'scan-wipe to N = 400 (counter rolls 10 -> 400)', intensity: 0.5 },
  { frame: 323, kind: 'crackle', description: 'A: the hot drop starts to spread — 469 contacts in the first recorded frame, 405, 313, 231 … decaying to ~45/frame by f332; B S-gauge turns red (falling)', intensity: 0.9 },
  { frame: 336, kind: 'crackle', description: 'steady gas crackle in both panels (~20-35 contacts/frame each); A keeps spreading, B keeps gathering, through f390', intensity: 0.35 },
  { frame: 356, kind: 'crackle', description: 'mid-window: A and B show the same recorded frame (k = 34) — the mirror point; crackle continues', intensity: 0.35 },
  { frame: 366, kind: 'whoosh', description: 'slow push-in on panel B begins (1.00 -> 1.06 by f390): a rising swell under the crackle', intensity: 0.35 },
  { frame: 381, kind: 'crackle', description: 'B: crescendo as the gas gathers — 46, 66, 84, 108, 144, 182, 231, 313, 405 contacts/frame (f381-389)', intensity: 0.8 },
  { frame: 390, kind: 'impact', description: 'B snaps shut into the drop (469 contacts) + verdict "!!" slams (red); strongest camera shake releases the push-in; C6 starts condensing', intensity: 1.0 },
  { frame: 391, kind: 'glitch', description: 'B tape tears (RGB slices) for ~10 frames: time tampered with', intensity: 0.6 },
  { frame: 392, kind: 'stamp', description: "THE ANSWER: stamps ▶ 正放 (A) / ◀◀ 倒放 (B), clocks switch to ▶ +02.33 s / ◀◀ 00.00 s (B's with the ◀◀ RGB split), B frame turns red", intensity: 0.75 },
  { frame: 398, kind: 'whoosh', description: 'gold arrows grow: after 方向 in the caption (f398-410) and across panel A from the t = 0 ghost drop (f400-418); the gutter HUD clears (f396-412)', intensity: 0.5 },
  { frame: 412, kind: 'silence', description: 'C6 「方向，出现了。」 fully condensed and held crisp (f412-436): the music thins under it', intensity: 0.1 },
  { frame: 422, kind: 'rewind', description: "B's tape is pulled out of its panel to the right in torn RGB slices (f422-436) as both panels retract (f426-444)", intensity: 0.5 },
  { frame: 426, kind: 'swarm', description: "A's 400 balls lift off (launches f426-433, each carrying its gas velocity) and pour on bowed paths into the word 很多 (complete by f453)", intensity: 0.7 },
  { frame: 436, kind: 'whoosh', description: 'C6 diffuses away (f436-450)', intensity: 0.2 },
  { frame: 442, kind: 'whoosh', description: 'card 7 condenses once the swarm has crossed line 1: 时间之箭 in gold (tracking widening to 0.5 em by ~f478), 藏在“ … ”之中。 around the word', intensity: 0.3 },
  { frame: 453, kind: 'chime', description: '很多 locks: the word is made of the 400 balls; the full sentence 「时间之箭，藏在“很多”之中。」 is complete ~f464 and held to f498', intensity: 0.5 },
  { frame: 496, kind: 'shimmer', description: '"many" evaporates (f496-514) as the sentence diffuses (f498-512); four balls survive and glide to P4 (f496-512)', intensity: 0.4 },
  { frame: 500, kind: 'sweep', description: 'the S03 box draws itself out of the top and bottom centre, turning the corners (f500-514)', intensity: 0.3 },
  { frame: 514, kind: 'click', description: "the box's sides meet at mid-height: the box is closed", intensity: 0.35 },
  { frame: 516, kind: 'tick', description: 'the divider seats (f506-516) — then near-silence for the OUT hold (S03 opens on a 咔)', intensity: 0.25 },
  { frame: 517, kind: 'silence', description: 'OUT hold f516-521: static frame, room tone', intensity: 0 },
];
